repository:
  homepage: "https://storybook.kreftforeningen.no"
  description: "Storybook for Kreftforeningen. UI components for the Kreftforeningen platform."
  topics:
    - storybook
    - kreftforeningen
    - ui
    - components
    - react
    - typescript
    - vite
    - tailwind
    - kf-component-library
